# Generated by Django 4.0.3 on 2023-05-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('idCarro', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca_modelo', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estacionamentos',
            fields=[
                ('idEstacionamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True, help_text='Formato <em>YYYT-MM-DD </em>')),
                ('hora_entrada', models.TimeField(auto_now_add=True, help_text='Formato <em>YYYT-MM-DD </em>')),
                ('data_saida', models.DateField(blank=True, help_text='Formato <em>YYYT-MM-DD </em>', null=True)),
                ('hora_saida', models.TimeField(blank=True, help_text='Formato <em>YYYT-MM-DD </em>', null=True)),
                ('fk_idCarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carros')),
            ],
        ),
        migrations.AddField(
            model_name='carros',
            name='fk_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
