# Generated by Django 4.0.3 on 2023-05-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_carros_alter_usuarios_idusuario_estacionamentos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='estacionamentos',
            options={'verbose_name_plural': 'Estacionamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuários'},
        ),
    ]
