# Generated by Django 4.0.3 on 2023-05-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_carros_options_alter_estacionamentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamentos',
            name='fk_idCarro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carros', verbose_name='Placa do Carro'),
        ),
    ]
