# Generated by Django 4.2.4 on 2023-12-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('bibliotecario', 'Permissão do Usuario Bibliotecario'), ('coordeandor', 'Permissão do Usuario Coordenador')]},
        ),
    ]
