# Generated by Django 4.2.4 on 2023-12-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('bibliotecario', 'Permissão do Usuario Bibliotecario'), ('coordenador', 'Permissão do Usuario Coordenador')]},
        ),
    ]
